version: '3.8'

services:
  spring-app:
    container_name: 'spring-app'
    build:
      context: .
    develop:
      watch:
        - path: build/libs
          action: rebuild
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    restart: always
    container_name: 'postgresql'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'testdb'
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql

volumes:
  postgres:
  pgadmin:
