services:

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.126.0@sha256:973747f78266a8ffec428417727e6b704559e9a30e4be8c1cca2899facd68689
    volumes:
      - ./otel-collector.yml:/otel-config.yaml
    command: [ "--config=/otel-config.yaml" ]
    ports:
      - "4317:4317"

volumes:
  pgdata:
